export const points: { [key: string]: string } = {
	N: `(nasion), Most anterior point on frontonasal suture`,
	S: `(sella), the midpoint of the cavity of sella turcica`,
	Or: `(orbitale), the lowest point on the inferior margin of the orbit`,
	Pt: `(Pterygo-maxillary fissure), Point at base of fissure where anterior and posterior wall meet. Anterior wall represents posterior surface of maxillary tuberosity`,
	A: `the innermost point on the contour of the premaxilla between anterior nasal spine and the incisor tooth`,
	B: `the innermost point on the contour of the mandible between the incisor tooth and the bony chin`,
	Ii: 'Incisor inferior (lower incisor tip)',
	Iia: 'Incisor inferior apex (lower incisor root)',
	Pg: `(pogonion), the most anterior point on the contour of the chin`,
	Me: `(menton), the most inferior point on the mandibular symphysis(i.e., the bottom of the chin)`,
	Gn: `(gnathion), Point located perpendicular on mandibular symphysis midway between pogonion and menton`,
	Go: `(gonion), the midpoint of the contour connecting the ramus and body of the mandible`,
	Ba: `(basion), the lowest point on the anterior margin of the foramen magnum, at the base of the clivus`,
	Po: `(porion), the midpoint of the upper contour of the external auditory canal (anatomic porion); or the midpoint of the upper contour of the metal ear rod of the cephalometer(machine porion)`,
	Isa: 'Incisor superior apex (upper incisor root)',
	Is: 'Incisor superior (upper incisor tip)',
	OLp: 'Occlusal Line, posterior point, distal tip of the first molar',
	OLa: 'Occlusal Line, anterior point, distal tip of the first premolar'
};
